site_name: fennland
site_author: fenn

repo_url: https://gitee.com/fennland/fennland
repo_name: Gitee

theme:
  name: material
  locale: zh_CN
  logo: img/icon.png # logo
  favicon: img/icon.png  # favicon

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - footnotes
  - tables
  - markdown_checklist.extension

plugins:
  - literate-nav:
      nav_file: README.md
      implicit_index: false

nav:
  - 欢迎: 'index.md'